In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Copy of 311_Service_Requests_2020.csv')

C:\Users\anwes\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (20,31,32) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
df.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,45285347,01/01/2020 12:00:00 AM,01/10/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,3 or More,Restaurant/Bar/Deli/Bakery,11229.0,3442 NOSTRAND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.600129,-73.941843,"(40.6001292057807, -73.94184291675883)"
1,45285651,01/01/2020 12:00:00 AM,01/02/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Restaurant/Bar/Deli/Bakery,10458.0,2701 DECATUR AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.864866,-73.888783,"(40.86486556770799, -73.88878325729915)"
2,45285821,01/01/2020 12:00:00 AM,01/02/2020 09:50:09 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Other (Explain Below),11203.0,5707 CHURCH AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.652536,-73.923540,"(40.65253575905768, -73.92353994017134)"
3,45287907,01/01/2020 12:00:00 AM,01/02/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,3 or More,Restaurant/Bar/Deli/Bakery,11214.0,1602 SHORE PARKWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.595653,-74.000173,"(40.59565343138651, -74.00017283917487)"
4,45288240,01/01/2020 12:00:00 AM,01/02/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Restaurant/Bar/Deli/Bakery,11385.0,1717 CORNELIA STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.700366,-73.905438,"(40.700366489799876, -73.90543829006366)"

In [4]:
df.columns

Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Complaint Type', 'Descriptor', 'Location Type', 'Incident Zip',
       'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
       'Intersection Street 1', 'Intersection Street 2', 'Address Type',
       'City', 'Landmark', 'Facility Type', 'Status', 'Due Date',
       'Resolution Description', 'Resolution Action Updated Date',
       'Community Board', 'BBL', 'Borough', 'X Coordinate (State Plane)',
       'Y Coordinate (State Plane)', 'Open Data Channel Type',
       'Park Facility Name', 'Park Borough', 'Vehicle Type',
       'Taxi Company Borough', 'Taxi Pick Up Location', 'Bridge Highway Name',
       'Bridge Highway Direction', 'Road Ramp', 'Bridge Highway Segment',
       'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [5]:
print(df['Incident Zip'].unique())                         # Prints all zip codes 

Zip = float(input("Choose the Incident Zip"))              # Accepts a particular Zip code
data = df.loc[(df['Incident Zip'] == Zip )]   

data =pd.DataFrame(data['Complaint Type'].value_counts())
data =data.reset_index()
data = data.rename(columns={'index': 'Complaint_Type','Complaint Type': 'No. of Occurences'})
data = data.set_index('Complaint_Type')
data = data.head(10)
data                                                       # Print top 10 compalint_type with number

[11229. 10458. 11203. 11214. 11385. 11225. 11421. 10455. 11215. 11210.
 10468. 10025. 11103. 11222. 10016. 11206. 11221. 11238. 11223. 11219.
 10465. 10040. 11228. 10472. 11373. 10463. 10031. 10460. 11217. 10012.
 10002. 10466. 11209. 11237. 10034. 11220. 10456. 11235. 10470. 10013.
 10452. 11420. 11230. 10017. 11378. 10464. 10173. 11212. 11231. 10033.
 11218. 10462. 10003. 11226. 11423. 11361. 11236. 11366. 10009. 11372.
 10309. 11368. 11201. 11432. 11691. 11204. 10039. 11375. 11233. 10312.
 10024. 11365. 11370. 10029. 11358. 10471. 10314. 11207. 10022. 10032.
 11356. 10014. 11213. 10026. 10453. 11419. 10459. 11105. 10461. 11211.
 11357. 11434. 11428. 10473. 10037. 11426. 10307. 11377. 10128. 10305.
 10306. 11354. 10451. 10467.    nan 10010. 10028. 11208. 10457. 10038.
 10027. 11104. 11224. 11379. 10310. 11418. 11369. 11414. 11422. 11249.
 11360. 11364. 11232. 11205. 11415. 11106. 10011. 11102. 10021. 10007.
 10469. 11412. 11234. 10075. 10454. 11374. 11435. 10035. 10004. 11216.
 10030. 11694. 11413. 10036. 10303. 10302. 10475. 10304. 11417. 11101.
 10282. 11692. 10023. 11433. 10018. 11693. 11362. 10301. 11367. 10065.
 11416. 10019. 11239. 11430. 10001. 10121. 10105. 11355. 10308. 10279.
 11004. 11436. 10005. 10474. 11411. 11427. 10044. 10119. 11371. 11429.
 10169. 11363. 10177. 11040. 11359. 10000. 10006. 10178. 10280. 11001.
 10174. 10069. 11109. 11697. 11005. 10020. 12345. 10171. 10120. 10278.
 10112. 10172. 10281. 10041. 10168. 11695. 10165. 10162. 10103. 10151.
 11242. 10118. 10152. 10271. 10154. 10155. 10110. 10045. 10123. 10170.
 10166. 11251. 10122. 10158. 10179. 10111. 10055. 10106. 10176. 11241.
 10107. 10115.    83. 10153. 10167. 10175. 10048.]
Choose the Incident Zip10025

                             No. of Occurences
Complaint_Type
Noise - Residential                       2952
Noise - Street/Sidewalk                   2128
HEAT/HOT WATER                            1885
Noise                                     1131
Illegal Parking                            792
Noise - Vehicle                            787
Non-Emergency Police Matter                773
Rodent                                     691
Illegal Fireworks                          672
UNSANITARY CONDITION                       565

In [6]:
data = pd.Series(data.iloc[:,0])

In [7]:
data

Complaint_Type
Noise - Residential            2952
Noise - Street/Sidewalk        2128
HEAT/HOT WATER                 1885
Noise                          1131
Illegal Parking                 792
Noise - Vehicle                 787
Non-Emergency Police Matter     773
Rodent                          691
Illegal Fireworks               672
UNSANITARY CONDITION            565
Name: No. of Occurences, dtype: int64